targets:
  $default:
    builders:
      sequelize_orm_generator|sequelize_model_builder:
        enabled: true
        options:
      sequelize_orm_generator|models_registry_builder:
        enabled: true
