targets:
  $default:
    builders:
      sequelize_dart_generator|sequelize_model_builder:
        enabled: true
        options:
      sequelize_dart_generator|models_registry_builder:
        enabled: true
