targets:
  $default:
    builders:
      sequelize_dart_generator|sequelize_model_builder:
        enabled: true
        options:
          # naming_strategy: "singular"
          # naming_strategy: "plural"
