-- Seed Data Script (PostgreSQL)
-- Creates 100 users, 100 posts, and 100 post_details
-- Run this after migrations to populate the database with test data
-- Created: 2024-12-06

-- ============================================
-- Seed Users (100 records)
-- ============================================

INSERT INTO users (email, first_name, last_name, created_at, updated_at) VALUES
('john.smith0@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson1@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams2@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown3@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones4@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia5@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller6@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis7@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez8@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez9@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith10@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson11@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams12@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown13@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones14@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia15@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller16@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis17@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez18@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez19@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith20@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson21@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams22@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown23@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones24@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia25@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller26@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis27@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez28@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez29@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith30@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson31@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams32@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown33@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones34@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia35@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller36@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis37@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez38@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez39@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith40@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson41@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams42@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown43@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones44@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia45@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller46@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis47@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez48@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez49@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith50@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson51@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams52@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown53@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones54@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia55@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller56@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis57@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez58@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez59@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith60@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson61@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams62@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown63@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones64@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia65@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller66@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis67@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez68@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez69@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith70@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson71@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams72@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown73@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones74@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia75@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller76@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis77@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez78@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez79@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith80@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson81@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams82@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown83@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones84@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia85@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller86@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis87@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez88@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez89@example.com', 'Henry', 'Martinez', NOW(), NOW()),
('john.smith90@example.com', 'John', 'Smith', NOW(), NOW()),
('jane.johnson91@example.com', 'Jane', 'Johnson', NOW(), NOW()),
('bob.williams92@example.com', 'Bob', 'Williams', NOW(), NOW()),
('alice.brown93@example.com', 'Alice', 'Brown', NOW(), NOW()),
('charlie.jones94@example.com', 'Charlie', 'Jones', NOW(), NOW()),
('diana.garcia95@example.com', 'Diana', 'Garcia', NOW(), NOW()),
('eve.miller96@example.com', 'Eve', 'Miller', NOW(), NOW()),
('frank.davis97@example.com', 'Frank', 'Davis', NOW(), NOW()),
('grace.rodriguez98@example.com', 'Grace', 'Rodriguez', NOW(), NOW()),
('henry.martinez99@example.com', 'Henry', 'Martinez', NOW(), NOW());

-- ============================================
-- Seed Posts (100 records)
-- ============================================

INSERT INTO posts (title, content, user_id, created_at, updated_at) VALUES
('Getting Started with Dart', 'This is a comprehensive guide... (Post #1)', 1, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #2)', 2, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #3)', 3, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #4)', 4, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #5)', 5, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #6)', 6, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #7)', 7, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #8)', 8, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #9)', 9, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #10)', 10, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #11)', 11, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #12)', 12, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #13)', 13, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #14)', 14, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #15)', 15, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #16)', 16, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #17)', 17, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #18)', 18, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #19)', 19, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #20)', 20, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #21)', 21, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #22)', 22, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #23)', 23, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #24)', 24, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #25)', 25, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #26)', 26, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #27)', 27, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #28)', 28, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #29)', 29, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #30)', 30, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #31)', 31, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #32)', 32, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #33)', 33, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #34)', 34, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #35)', 35, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #36)', 36, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #37)', 37, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #38)', 38, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #39)', 39, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #40)', 40, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #41)', 41, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #42)', 42, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #43)', 43, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #44)', 44, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #45)', 45, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #46)', 46, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #47)', 47, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #48)', 48, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #49)', 49, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #50)', 50, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #51)', 51, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #52)', 52, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #53)', 53, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #54)', 54, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #55)', 55, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #56)', 56, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #57)', 57, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #58)', 58, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #59)', 59, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #60)', 60, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #61)', 61, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #62)', 62, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #63)', 63, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #64)', 64, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #65)', 65, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #66)', 66, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #67)', 67, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #68)', 68, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #69)', 69, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #70)', 70, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #71)', 71, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #72)', 72, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #73)', 73, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #74)', 74, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #75)', 75, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #76)', 76, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #77)', 77, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #78)', 78, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #79)', 79, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #80)', 80, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #81)', 81, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #82)', 82, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #83)', 83, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #84)', 84, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #85)', 85, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #86)', 86, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #87)', 87, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #88)', 88, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #89)', 89, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #90)', 90, NOW(), NOW()),
('Getting Started with Dart', 'This is a comprehensive guide... (Post #91)', 91, NOW(), NOW()),
('Advanced Sequelize Patterns', 'In this article, we will explore... (Post #92)', 92, NOW(), NOW()),
('Database Design Best Practices', 'Let''s dive deep into... (Post #93)', 93, NOW(), NOW()),
('Performance Optimization Tips', 'Understanding the fundamentals... (Post #94)', 94, NOW(), NOW()),
('Understanding Relations', 'Best practices suggest... (Post #95)', 95, NOW(), NOW()),
('Migration Strategies', 'When working with... (Post #96)', 96, NOW(), NOW()),
('Testing Database Code', 'It''s important to consider... (Post #97)', 97, NOW(), NOW()),
('Security Best Practices', 'The key concepts include... (Post #98)', 98, NOW(), NOW()),
('Scaling Applications', 'We''ll cover several topics... (Post #99)', 99, NOW(), NOW()),
('Monitoring and Logging', 'This tutorial will walk you through... (Post #100)', 100, NOW(), NOW());

-- ============================================
-- Seed Post Details (100 records)
-- ============================================

INSERT INTO post_details (post_id, views, likes, metadata, created_at, updated_at) VALUES
(1, 1234, 56, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(2, 2345, 67, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(3, 3456, 78, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(4, 4567, 89, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(5, 5678, 90, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(6, 6789, 101, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(7, 7890, 112, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(8, 8901, 123, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(9, 9012, 134, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(10, 1023, 145, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(11, 2134, 156, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(12, 3245, 167, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(13, 4356, 178, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(14, 5467, 189, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(15, 6578, 190, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(16, 7689, 201, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(17, 8790, 212, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(18, 9801, 223, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(19, 1092, 234, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(20, 2103, 245, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(21, 3214, 256, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(22, 4325, 267, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(23, 5436, 278, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(24, 6547, 289, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(25, 7658, 290, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(26, 8769, 301, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(27, 9870, 312, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(28, 1981, 323, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(29, 2092, 334, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(30, 3103, 345, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(31, 4214, 356, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(32, 5325, 367, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(33, 6436, 378, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(34, 7547, 389, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(35, 8658, 390, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(36, 9769, 401, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(37, 1870, 412, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(38, 2981, 423, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(39, 3092, 434, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(40, 4103, 445, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(41, 5214, 456, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(42, 6325, 467, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(43, 7436, 478, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(44, 8547, 489, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(45, 9658, 490, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(46, 1769, 501, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(47, 2870, 512, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(48, 3981, 523, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(49, 4092, 534, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(50, 5103, 545, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(51, 6214, 556, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(52, 7325, 567, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(53, 8436, 578, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(54, 9547, 589, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(55, 1658, 590, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(56, 2769, 601, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(57, 3870, 612, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(58, 4981, 623, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(59, 5092, 634, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(60, 6103, 645, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(61, 7214, 656, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(62, 8325, 667, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(63, 9436, 678, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(64, 1547, 689, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(65, 2658, 690, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(66, 3769, 701, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(67, 4870, 712, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(68, 5981, 723, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(69, 6092, 734, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(70, 7103, 745, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(71, 8214, 756, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(72, 9325, 767, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(73, 1436, 778, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(74, 2547, 789, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(75, 3658, 790, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(76, 4769, 801, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(77, 5870, 812, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(78, 6981, 823, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(79, 7092, 834, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(80, 8103, 845, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(81, 9214, 856, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(82, 1325, 867, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(83, 2436, 878, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(84, 3547, 889, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(85, 4658, 890, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(86, 5769, 901, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(87, 6870, 912, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(88, 7981, 923, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(89, 8092, 934, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(90, 9103, 945, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(91, 1214, 956, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(92, 2325, 967, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(93, 3436, 978, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(94, 4547, 989, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(95, 5658, 990, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(96, 6769, 1001, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(97, 7870, 1012, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(98, 8981, 1023, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(99, 9092, 1034, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW()),
(100, 10103, 1045, '{"tags":["dart","sequelize","database"],"category":"tutorial"}'::jsonb, NOW(), NOW());

