analyzer:
  errors:
    invalid_use_of_protected_member: ignore
    non_constant_identifier_names: ignore
include: ../../analysis_options.yaml

linter:
  rules:
    # This library intentionally uses print for bridge logging and SQL formatting output
    avoid_print: false
