import 'package:sequelize_dart/src/query/query/query.dart';

/// Base class for increment operations
/// This class handles parsing and JSON conversion for increment operations
class IncrementOptions {
  /// Map of field names to increment values
  final Map<String, dynamic> fields;

  /// Optional query conditions (where clause)
  final Query? query;

  IncrementOptions({
    required this.fields,
    this.query,
  });

  /// Convert to JSON for transmission to query engine
  Map<String, dynamic> toJson() {
    return {
      'fields': fields,
      'query': query?.toJson(),
    };
  }

  /// Create IncrementOptions from JSON
  // factory IncrementOptions.fromJson(Map<String, dynamic> json) {
  //   return IncrementOptions(
  //     fields: json['fields'] as Map<String, dynamic>,
  //     query: json['query'] != null ? Query.fromJson(json['query'] as Map<String, dynamic>) : null,
  //   );
  // }
}

/// Generated increment class for specific models
/// This class will be generated by the build_runner for each model
/// and will only include numeric fields (int, double, num)
class ModelIncrement<T> {
  /// The model instance to increment
  final T modelInstance;

  /// The query engine to use
  final dynamic queryEngine;

  /// The model name
  final String modelName;

  ModelIncrement({
    required this.modelInstance,
    required this.queryEngine,
    required this.modelName,
  });

  /// Execute the increment operation
  Future<T> call(IncrementOptions options) async {
    final result = await queryEngine.increment(
      modelName: modelName,
      fields: options.fields,
      query: options.query,
    );
    return result;
  }
}
